fix(api-core): use correct region param for permissions call inside o…
Availity/sdk-js pull request #307
Opened 2021-03-16 18:39 UTC by stevenviar

Because the correct param to pass a region to `organizations` is `regions.code`, the region isn't currently getting passed to the `axi-user-permissions` request inside of the organizations resource unless the user is incorrectly sending it as `region`.

Christie and I talked about making it so the user could pass either `region` or `regions.code`, but when I was trying to accommodate this it seemed a little messy.

2021-03-17 15:50 UTC, chrishavekost requested changes
Maybe we should be calling out in the docs that the `region` param coming from the user's passed in `data` object is specifically for the `axi-user-permissions` call. Your change to use `data[regions.code]` will work fine when user is filtering by one region, but the organization service accepts multiple regions under `regions.code`, while `axi-user-permissions` will only accept one.

Generally if you're filtering organizations you are probably just passing in one region anyway, but this would still introduce the potential for an array of regions to get passed to `axi-user-permissions`, so I think we should account for that.. maybe we can pull out the `region` param before the organization call is made (since it's not doing anything anyway), keep the existing `{ region } = data;` for `axi-user-permissions` so we don't break any existing usage, and make a note in the docs about what `regions.code` and `region` are for. Does that sound alright?

2021-03-18 18:07 UTC, stevenviar commented
So you're saying we should allow both `region` and `regions.code` to be passed? I think that would be fine, but are both needed for most filtering scenarios? It seems like when you filter by permission and region the `regions.code` isn't really necessary. I'm just trying to think of how the docs should be worded to suggest when `region` and `regions.code` should be used.

2021-03-19 14:54 UTC, chrishavekost commented
I think we basically keep the same behavior we have now where if a user passes `regions.code` to the organizations call we don't do anything with it in the user permissions call.

I don't think both `regions.code` and `region` are technically needed for most filtering scenarios, but we don't want to remove user's ability to pass multiple regions in `regions.code`, and we don't want to extract `region` from `regions.code` for user permissions because we'd have to introduce some sort of logic for when a user passes multiple regions, since we can only use one of those.

I think the docs just need to be clear that `region` is used only for the user permissions call, and that `regions.code` is for the organizations call. Also if `regions.code` is used, it will make the result set to filter against smaller

2021-03-31 21:33 UTC, chrishavekost approved these changes

2021-04-01 13:26 UTC, merged