Feat/api axios types
Availity/sdk-js pull request #387
Opened 2021-09-15 19:51 UTC by jordan-a-young

This PR contains a declaration file for `@availity/api-axios`. I don't think it is 100% perfect, but my hope is this can serve as a starting point and the types can be refined as we go. The resources do not have their specific response shape added, but the user can add it on their end to get around this for now.

I added formatting scripts for `@availity/api-axios` and `@availity/api-core` and ran them. 

Finally, I tried to cleanup some of the docs. This mostly involved formatting and how we display responses. eg: switch from "\```js" to "\```json"

2021-09-15 20:43 UTC, danielpickett approved these changes

2021-09-16 15:24 UTC, chrishavekost requested changes

2021-09-16 15:24 UTC, chrishavekost commented on docusaurus/docs/resources/native-form.md
> +- type: String. Override the magneto integration type. Defaults to "saml"
As of 4.0.0 this no longer defaults to `saml`, I missed these docs in my PR.

2021-09-16 15:24 UTC, chrishavekost commented on docusaurus/docs/resources/native-form.md
> +- formAttributes: Object. Set/override the form attributes like `target`, `method`, and `action`. `method` defaults to "post", `action` will default to "\`/ms/api/availity/internal/spc/magneto/sso/v1
`action` now defaults to `/ms/api/availity/internal/spc/magneto/sso/v1/${typeLower}/${spaceId}`
where `typeLower` is either `saml` or `openid`

2021-09-16 15:24 UTC, chrishavekost commented on docusaurus/docs/resources/native-form.md
> +- type: String. Override the magneto integration type. Defaults to "saml"
There's also one more param now for `clientId` which is optional and defaults to `'clientId'` if not provided.

2021-09-16 15:24 UTC, chrishavekost commented on docusaurus/docs/resources/native-form.md
>  nativeForm(
`nativeForm` is now async so this should be `await nativeForm`
There's also the possibility of errors/promise rejections now that we are (potentially) fetching the proper sso type, so we should probably document this inside a try/catch with error handling.

2021-09-16 18:06 UTC, chrishavekost approved these changes
🏆

2021-09-16 18:34 UTC, merged